Repository CoorpAcademy/mobile, pull requests merged in 2019-07, with the labels that each got.

#358 Dont play feedback sounds on silent mode :)
  src/modules/audio-player.js
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review

#362 Align the section title with the first item
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/catalog-section.js
Labels: pr: :bug: Bug Fix

#363 Fixes the calculated offset depending on hidden sections
  src/containers/catalog.js
  src/modules/sections.js
  src/modules/sections.test.js
Labels: pr: :bug: Bug Fix

#359 Open mail in magic link steps
  android/app/build.gradle
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  ios/Coorpacademy/Info.plist
  jest-setup.js
  package.json
  src/components/__snapshots__/authentication-details.stories.storyshot
  src/components/__snapshots__/authentication-steps.stories.storyshot
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/authentication-steps.js
  src/components/authentication.js
  src/modules/inbox.js
  src/modules/inbox.test.js
  src/screens/authentication-details.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :page_facing_up: Waiting for translations, pr: :rocket: New feature

#365 Fix level end header home button
  src/components/__snapshots__/header-back-button.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/header-back-button.js
  src/components/level-end.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#367 Fix/wrongly stored level
  src/layer/data/bundle.js
  src/modules/reference.js
  src/modules/reference.test.js
  src/redux/actions/progression.js
Labels: pr: :bug: Bug Fix

#366 Remove duplicate color
  src/components/__snapshots__/error-modal.stories.storyshot
  src/components/error-modal.js
  src/modules/theme.js
Labels: pr: :wrench: Refactoring

#369 Fix/language
  ios/Podfile.lock
  package.json
  src/layer/data/cards.js
  src/layer/data/sections.js
  src/layer/data/sections.test.js
  src/modules/uri.js
  src/modules/uri.test.js
  src/redux/actions/catalog/sections.js
  src/services/sections.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :soon: Waiting for CI

#370 Fix commit version displayed
  src/components/home.stories.js
Labels: pr: :bug: Bug Fix

#373 Fix next level on level end screen and completion update
  jest.config.unit.js
  package.json
  src/__fixtures__/chapters.js
  src/__fixtures__/disciplines.js
  src/__fixtures__/exit-nodes.js
  src/__fixtures__/levels.js
  src/__fixtures__/slides.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/__fixtures__/utils/mappers.js
  src/__fixtures__/utils/mappers.test.js
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/level-end.js
  src/components/level-end.stories.js
  src/containers/catalog-section-refreshable.js
  src/containers/catalog.js
  src/layer/data/_types.js
  src/layer/data/cards.js
  src/layer/data/chapters.js
  src/layer/data/chapters.test.js
  src/layer/data/content.js
  src/layer/data/content.test.js
  src/layer/data/disciplines.js
  src/layer/data/disciplines.test.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/layer/data/levels.js
  src/layer/data/levels.test.js
  src/layer/data/mappers.js
  src/layer/data/mappers.test.js
  src/layer/data/recommendations.js
  src/layer/data/recommendations.test.js
  src/modules/uri.js
  src/modules/uri.test.js
  src/redux/actions/catalog/cards.js
  src/redux/actions/catalog/cards.test.js
  src/redux/actions/catalog/cards/fetch.js
  src/redux/actions/catalog/cards/fetch.test.js
  src/redux/actions/catalog/cards/refresh.js
  src/redux/actions/catalog/cards/refresh.test.js
  src/redux/actions/catalog/cards/select.js
  src/redux/actions/catalog/cards/select.test.js
  src/redux/actions/catalog/sections.js
  src/redux/actions/catalog/sections.test.js
  src/redux/actions/progression.js
  src/redux/middlewares/update-card-on-progression-update.js
  src/redux/reducers/catalog.js
  src/redux/reducers/catalog.test.js
  src/redux/utils/state-extract.js
  src/screens/correction.js
  src/screens/correction.test.js
  src/screens/home.js
  src/screens/level-end.js
  src/screens/level-end.test.js
  src/services/recommendations.js
  src/utils/content.js
  src/utils/content.test.js
  src/utils/index.js
  src/utils/index.test.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#378 Fix Circle CI Build
  .circleci/config.yml
  .xcoderc
  yarn.lock
Labels: pr: :bug: Bug Fix

#381 Use everywere the app language as single source of truth
  src/app.js
  src/layer/data/bundle.js
  src/layer/data/bundle.test.js
  src/layer/data/index.js
  src/redux/actions/catalog/cards/select.js
  src/redux/actions/catalog/cards/select.test.js
  src/services/bundle.js
Labels: pr: :bug: Bug Fix

#375 Coverage create next progression
  jest.config.unit.js
  src/redux/actions/catalog/cards/select.js
  src/redux/actions/catalog/cards/select.test.js
  src/redux/actions/progression.js
  src/redux/actions/progressions/create-chapter-progression.js
  src/redux/actions/progressions/create-chapter-progression.test.js
  src/redux/actions/progressions/create-level-progression.js
  src/redux/actions/progressions/create-level-progression.test.js
  src/redux/actions/progressions/create-next-progression.js
  src/redux/actions/progressions/create-next-progressions.test.js
  src/redux/actions/progressions/select-progression.js
  src/redux/actions/progressions/select-progression.test.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/redux/middlewares/progressions-synchronization.js
  src/redux/middlewares/progressions-synchronization.test.js
  src/redux/utils/state-extract.test.js
  src/screens/correction.js
  src/screens/level-end.js
Labels: pr: :lollipop: Enhancement
