Repository CoorpAcademy/mobile, pull requests merged in 2019-05, with the labels that each got.

#283 Add documentation about iPhone 6 missing for Detox
  .github/TROUBLESHOOTING.md
Labels: pr: :memo: Documentation

#269 Bumping fastlane and plugins :outbox_tray:
  android/Gemfile.lock
  android/fastlane/Fastfile
  ios/Gemfile.lock
  ios/fastlane/Fastfile
Labels: pr: :lollipop: Enhancement

#285 Fix swipe hint animation: added resetAnimation
  src/containers/cards-swipable.js
Labels: pr: :soon: Waiting for CI

#290 Display modal when a platform has been disabled
  src/app.js
  src/containers/error-listener.js
  src/layer/data/progressions.test.js
  src/models/error.js
  src/modules/fetch.js
  src/modules/fetch.test.js
  src/redux/_types.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/redux/actions/brands.js
  src/redux/actions/brands.test.js
  src/redux/actions/cards.js
  src/redux/actions/cards.test.js
  src/redux/actions/progression.js
  src/redux/middlewares/error-handler.js
  src/redux/middlewares/error-handler.test.js
  src/redux/store.js
  src/screens/authentication.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#291 Enhance error modal UI on Android
  src/components/__snapshots__/error-modal.stories.storyshot
  src/components/error-modal.js
  src/components/header-back-button.js
  src/modules/theme.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#293 Fix error in android and modal UI change before its hidden
  src/layer/data/cards.js
  src/redux/reducers/ui/error.js
Labels: pr: :soon: Waiting for CI

#295 segregate signin with QR Code from magic link
  src/const.js
  src/containers/with-universal-links.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/screens/authentication-details.js
  src/screens/authentication.js
  src/types.js
Labels: pr: :lollipop: Enhancement

#297 improve gradient to handle Xtrem cases
  src/__fixtures__/assets/portrait-7-with-text.jpg
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/image-gradient.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/image-gradient.js
  src/components/image-gradient.stories.js
Labels: pr: :lollipop: Enhancement

#296 Fetch chapters bundle
  src/__fixtures__/chapter-bundle/basic.js
  src/__fixtures__/chapter-bundle/index.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/layer/data/_types.js
  src/layer/data/answers.js
  src/layer/data/cards.js
  src/layer/data/cards.test.js
  src/layer/data/chapters.js
  src/layer/data/clues.js
  src/layer/data/clues.test.js
  src/layer/data/content.js
  src/layer/data/content.test.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/layer/data/exit-nodes.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/layer/data/levels.js
  src/layer/data/progressions.js
  src/layer/data/slides.js
  src/redux/actions/bundle.js
  src/redux/actions/bundle.test.js
  src/redux/actions/cards.js
  src/redux/middlewares/bundle.js
  src/redux/middlewares/bundle.test.js
  src/redux/middlewares/discipline-bundle.js
  src/redux/reducers/bundle.js
  src/redux/reducers/bundle.test.js
  src/redux/store.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/services/bundle.js
  src/services/discipline-bundle.js
  src/services/index.js
Labels: pr: :rocket: New feature

#300 Fix authentication with QR code scan
  src/screens/authentication-details.js
Labels: pr: :bug: Bug Fix

#301 Force Roboto font for One Plus users
  android/app/src/main/assets/fonts/Roboto-Black.ttf
  android/app/src/main/assets/fonts/Roboto-BlackItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Bold.ttf
  android/app/src/main/assets/fonts/Roboto-BoldItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Italic.ttf
  android/app/src/main/assets/fonts/Roboto-Light.ttf
  android/app/src/main/assets/fonts/Roboto-LightItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Medium.ttf
  android/app/src/main/assets/fonts/Roboto-MediumItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Regular.ttf
  android/app/src/main/assets/fonts/Roboto-Thin.ttf
  android/app/src/main/assets/fonts/Roboto-ThinItalic.ttf
  src/components/__snapshots__/authentication-details.stories.storyshot
  src/components/__snapshots__/authentication-footer.stories.storyshot
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/card-correction.stories.storyshot
  src/components/__snapshots__/card-header.stories.storyshot
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item-author.stories.storyshot
  src/components/__snapshots__/catalog-item-badge.stories.storyshot
  src/components/__snapshots__/catalog-item-footer.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/clue-front-item.stories.storyshot
  src/components/__snapshots__/clue.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/drop-zone.stories.storyshot
  src/components/__snapshots__/error-modal.stories.storyshot
  src/components/__snapshots__/extralife.stories.storyshot
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/header-slide-title.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/html.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/__snapshots__/preview.stories.storyshot
  src/components/__snapshots__/progression.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-slider.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/text.stories.storyshot
  src/components/__snapshots__/version.stories.storyshot
  src/components/button.js
  src/components/card-header.js
  src/components/correction.js
  src/components/extralife.js
  src/components/header-slide-title.js
  src/components/html.js
  src/components/lives.js
  src/components/question-slider.js
  src/components/text.js
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review

#298 Extralife text anim
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/lives.js
  src/components/lives.stories.js
  src/containers/lives-animated.js
Labels: pr: :lollipop: Enhancement

#309 Feat/catalog item placeholder
  package.json
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/placeholder.stories.storyshot
  src/components/catalog-item.js
  src/components/catalog-item.stories.js
  src/components/catalog.js
  src/components/catalog.stories.js
  src/components/placeholder.js
  src/components/placeholder.stories.js
  src/redux/utils/state-extract.js
  src/stories.js
  yarn.lock
Labels: pr: :lollipop: Enhancement
