Repository CoorpAcademy/mobile, pull requests merged in 2019-10, with the labels that each got.

#428 Progression meta
  src/__fixtures__/progression.js
  src/layer/data/index.js
  src/layer/data/progressions-aggregation.test.js
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/redux/actions/progressions/synchronize.js
  src/utils/progressions.js
  src/utils/progressions.test.js
Labels: pr: :construction: Work In Progress

#431 Fix high score at level end
  __e2e__/correction.fast-slide.test.js
  __e2e__/correction.god-mode.test.js
  __e2e__/level-end.test.js
  __e2e__/progression.test.js
  app.json
  package.json
  src/__fixtures__/cards.js
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/levels.js
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/screen.stories.storyshot
  src/components/__snapshots__/tooltip.stories.storyshot
  src/components/header-slide-right.js
  src/components/level-end.js
  src/components/level-end.stories.js
  src/components/question.js
  src/components/screen.js
  src/components/screen.stories.js
  src/components/tooltip.js
  src/components/tooltip.stories.js
  src/layer/data/index.js
  src/layer/data/levels.test.js
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/redux/actions/progressions/create-next-progression.js
  src/redux/actions/progressions/create-next-progressions.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/screens/level-end.js
  src/screens/level-end.test.js
  src/screens/question.js
  src/screens/question.test.js
  src/services/progressions.js
  src/services/progressions.test.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :white_check_mark: Enhance tests

#432 Adds lottie package to display After Effects animations
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/assets/animations/heart.json
  src/assets/animations/lock.json
  src/components/__snapshots__/heart.stories.storyshot
  src/components/__snapshots__/lock.stories.storyshot
  src/components/heart.js
  src/components/heart.stories.js
  src/components/lock.js
  src/components/lock.stories.js
  src/stories.js
  yarn.lock
Labels: pr: :rocket: New feature, pr: 🔭💻 R&D

#427 Hero content from aggregations
  __e2e__/dashboard.test.js
  __e2e__/hero.test.js
  __e2e__/level-end.test.js
  package.json
  src/__fixtures__/hero-recommendation.js
  src/__fixtures__/levels.js
  src/__fixtures__/progression.js
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/hero.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/hero.js
  src/components/home.js
  src/components/home.stories.js
  src/components/level-end.js
  src/containers/catalog.js
  src/containers/catalog.test.js
  src/layer/data/_types.js
  src/layer/data/cards.js
  src/layer/data/cards.test.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/layer/data/language.test.js
  src/layer/data/levels.js
  src/layer/data/levels.test.js
  src/layer/data/mappers.js
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/layer/data/recommendations.js
  src/layer/data/recommendations.test.js
  src/layer/data/sections.js
  src/modules/progression-aggregation-by-content/aggregate.js
  src/modules/progression-aggregation-by-content/index.js
  src/modules/progression-aggregation-by-content/test/aggregate.test.js
  src/modules/progression-aggregation-by-content/test/completion.test.js
  src/modules/progression-aggregation-by-content/test/fixtures/progression.js
  src/modules/progression-aggregation-by-content/test/fixtures/progressions.js
  src/modules/progression-aggregation-by-content/test/map-value.test.js
  src/modules/progression-aggregation-by-content/test/non-regression.test.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/redux/middlewares/update-card-on-progression-update.test.js
  src/screens/home.js
  src/screens/home.test.js
  src/services/brands.test.js
  src/services/hero.js
  src/services/hero.test.js
  src/services/progressions.js
  src/types.js
  src/utils/progressions.js
  src/utils/progressions.test.js
  yarn.lock
Labels: pr: :rocket: New feature

#434 Use disciplineUniversalRef
  package.json
  src/__fixtures__/levels.js
  src/layer/data/cards.js
  src/layer/data/cards.test.js
  src/layer/data/mappers.js
  yarn.lock
Labels: pr: :bug: Bug Fix

#435 Change to white logo
  android/app/src/main/res/mipmap-hdpi/icon.png
  android/app/src/main/res/mipmap-mdpi/icon.png
  android/app/src/main/res/mipmap-xhdpi/icon.png
  android/app/src/main/res/mipmap-xxhdpi/icon.png
  android/app/src/main/res/mipmap-xxxhdpi/icon.png
  ios/Coorpacademy/Images.xcassets/SplashIcon.imageset/Icon-1024.png
  ios/Coorpacademy/Images.xcassets/SplashIcon.imageset/Icon-256.png
  ios/Coorpacademy/Images.xcassets/SplashIcon.imageset/Icon-512.png
Labels: pr: :lollipop: Enhancement
