Repository CoorpAcademy/mobile, pull requests merged in 2019-06, with the labels that each got.

#332 Support 64 bit Arm(Architecture) for JavascriptCore on Androids
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/build.gradle
  package.json
  yarn.lock
Labels: pr: :bug: Bug Fix

#329 Fix correction card android overflow bug
  src/components/__snapshots__/card-correction.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/card-correction.js
  src/components/card.js
Labels: pr: :bug: Bug Fix, pr: :no_entry: Do not merge

#337 Dont use default react-native's gradle
  android/app/build.gradle
Labels: pr: :lollipop: Enhancement

#340 Adding watchman on publish_ios for bundling the app
  .circleci/config.yml
Labels: pr: :bug: Bug Fix

#344 Fix level end card bug on display and refreshcards
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/level-end.js
  src/layer/data/cards.js
Labels: pr: :bug: Bug Fix

#342 Fix Storybook
  metro.config.js
Labels: pr: :bug: Bug Fix

#341 Remove Refresh Control due to its integration on flatlist
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/catalog.js
Labels: pr: :lollipop: Enhancement, pr: 🔭💻 R&D

#345 Dashboard sections fetch
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/catalog-section.js
  src/components/catalog.js
  src/components/catalog.stories.js
  src/components/home.js
  src/containers/catalog-section-refreshable.js
  src/containers/catalog.js
  src/layer/data/cards.test.js
  src/layer/data/sections.js
  src/layer/data/sections.test.js
  src/redux/actions/catalog/sections.js
  src/redux/actions/catalog/sections.test.js
  src/redux/reducers/catalog.js
  src/redux/reducers/catalog.test.js
  src/services/sections.js
Labels: pr: :rocket: New feature

#347 Feat/question place holder
  .circleci/config.yml
  index.js
  src/components/__snapshots__/catalog-item-placeholder.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/header-slide-title.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/__snapshots__/placeholder-circle.stories.storyshot
  src/components/__snapshots__/placeholder-line.stories.storyshot
  src/components/__snapshots__/placeholder.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/slide-footer-item-placeholder.stories.storyshot
  src/components/__snapshots__/tab-bar-slide-placeholder.stories.storyshot
  src/components/header-slide-right.js
  src/components/header-slide-right.stories.js
  src/components/header-slide-title.js
  src/components/header-slide-title.stories.js
  src/components/lives.js
  src/components/lives.stories.js
  src/components/placeholder-circle.js
  src/components/placeholder-circle.stories.js
  src/components/placeholder-line.js
  src/components/placeholder.js
  src/components/question.js
  src/components/question.stories.js
  src/containers/header-slide-right.js
  src/containers/header-slide-title.js
  src/containers/header-slide-title.test.js
  src/containers/tab-bar-slide.js
  src/screens/home.js
  src/screens/question.js
  src/stories.js
Labels: pr: :rocket: New feature

#349 FastSlide Icon
  package.json
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/__snapshots__/slide-footer-item-placeholder.stories.storyshot
  src/components/__snapshots__/tab-bar-slide-placeholder.stories.storyshot
  src/components/lives.js
  src/modules/theme.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: 🔭💻 R&D

#351 Reduce the cards padding and remove rounded footer
  __e2e__/utils.js
  jest.config.e2e.js
  src/__fixtures__/chapter-bundle/index.js
  src/__fixtures__/chapter-bundle/template.js
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/rounded-footer.stories.storyshot
  src/components/catalog-section.js
  src/components/home.js
  src/components/rounded-footer.js
  src/components/rounded-footer.stories.js
  src/const.js
  src/containers/rounded-footer-animated.js
  src/stories.js
  src/types.js
Labels: pr: :lollipop: Enhancement

#352 Use bundle to use match
  package.json
Labels: pr: :wrench: Refactoring

#343 Feedback sonore
  android/app/build.gradle
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  assets-transformer.js
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  jest-setup.js
  jest.config.unit.js
  package.json
  src/assets/sounds/failure-level.mp3
  src/assets/sounds/good-answer.mp3
  src/assets/sounds/success-level.mp3
  src/assets/sounds/wrong-answer.mp3
  src/modules/audio-player.js
  src/screens/correction.js
  src/screens/level-end.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review, pr: :rocket: New feature, pr: 🔭💻 R&D

#356 Fix section title on Android
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/catalog-section.js
Labels: pr: :bug: Bug Fix

#350 testing more workers
  .circleci/config.yml
Labels: pr: :no_entry: Do not merge
