Repository CoorpAcademy/mobile, pull requests merged in 2019-12, with the labels that each got.

#453 Adding User-Agent for mobile
  jest-setup.js
  src/layer/data/progressions.test.js
  src/modules/fetch.js
  src/modules/fetch.test.js
Labels: pr: :lollipop: Enhancement

#454 Fix/User-Agent
  jest-setup.js
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/version.stories.storyshot
  src/layer/data/progressions.test.js
  src/modules/fetch.js
  src/modules/fetch.test.js
  src/modules/version.unit.json
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :no_entry: Do not merge

#455 migration script
  jest.config.unit.js
  package.json
  src/migrations/index.js
  src/migrations/tests/index.test.js
  src/migrations/types.js
  yarn.lock
Labels: pr: :rocket: New feature

#457 Job progressions
  flow-typed/npm/react-native-splash-screen_vx.x.x.js
  jest-setup.js
  src/migrations/index.js
  src/migrations/index.test.js
  src/migrations/runner.js
  src/migrations/runner.test.js
  src/migrations/scripts/fix-progressions-answers/index.js
  src/migrations/scripts/fix-progressions-answers/index.test.js
  src/migrations/types.js
  src/screens/authentication.js
  src/screens/authentication.test.js
Labels: pr: :bug: Bug Fix, pr: :mag_right: Need functional review, pr: :rocket: New feature

#415 Monitoring
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/build.gradle
  android/settings.gradle
  flow-typed/custom/app-store-link_vx.x.x.js
  flow-typed/custom/bson.js
  flow-typed/custom/cross-fetch_v3.x.x.js
  flow-typed/custom/detox_vx.x.x.js
  flow-typed/custom/jwt-decode.js
  flow-typed/custom/react-native-exception-handler_vx.x.x.js
  flow-typed/custom/react-native-keyboard-aware-scroll-view_v0.8.x.js
  flow-typed/custom/react-native-linear-gradient_vx.x.x.js
  flow-typed/custom/react-native-offline_v5.x.x.js
  flow-typed/custom/react-native-portal_vx.x.x.js
  flow-typed/custom/react-native-qrcode-scanner_vx.x.x.js
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/app.js
  src/containers/with-analytics.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/layer/data/logger.js
  src/layer/data/logger.test.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/services/index.js
  src/services/logger.js
  src/types.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :bulb: POC, pr: :rocket: New feature, pr: 🔭💻 R&D

#462 Fix subtitle statement and author without label
  src/components/__snapshots__/catalog-item-footer.stories.storyshot
  src/components/catalog-item-footer.js
  src/components/catalog-item-footer.stories.js
Labels: pr: :bug: Bug Fix
