Repository CoorpAcademy/mobile, pull requests merged in 2019-02, with the labels that each got.

#71 Add loader component
  src/components/__snapshots__/loader.stories.storyshot
  src/components/loader.js
  src/components/loader.stories.js
  src/stories.js
Labels: pr: :lollipop: Enhancement

#87 replace fr fixture by en fixture
  src/__fixtures__/onboarding-course/chapters.js
  src/__fixtures__/onboarding-course/discipline.js
  src/__fixtures__/onboarding-course/slides.js
Labels: pr: :lollipop: Enhancement

#88 Fix bug with leve-end screen when theres at least one live
  src/components/level-end.js
  src/components/level-end.stories.js
  src/screens/correction.js
  src/screens/level-end.js
Labels: pr: :bug: Bug Fix

#94 Split tests in few files
  .circleci/config.yml
  __e2e__/lesson.test.js
  __e2e__/lives.test.js
  __e2e__/progression.test.js
  __e2e__/questions.test.js
  __e2e__/slide.test.js
  package.json
  src/__fixtures__/chapters.js
  src/__fixtures__/discipline-bundle/adaptive.js
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/medias.js
  src/__fixtures__/questions.js
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/__snapshots__/progression-bar.stories.storyshot
  src/components/__snapshots__/progression.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/catalog.js
  src/components/level-end.js
  src/components/level-end.stories.js
  src/components/lives.js
  src/components/progression-bar.js
  src/components/question.js
  src/const.js
  src/containers/network-info-listener.js
  src/layer/data/answers.test.js
  src/layer/data/clues.test.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/layer/data/mappers.test.js
  src/layer/data/slides.test.js
  src/screens/correction.js
  src/screens/level-end.js
  src/screens/question.js
  src/types.js
Labels: pr: :wrench: Refactoring

#95 Fix brew cache linked
  .circleci/config.yml
Labels: pr: :wrench: Refactoring

#90 Feature/connect header
  __e2e__/header.test.js
  scripts/pull-translations.js
  src/__fixtures__/levels.js
  src/__fixtures__/onboarding-course/discipline.js
  src/components/__snapshots__/header-slide-title.stories.storyshot
  src/components/header-slide-title.js
  src/components/header-slide-title.stories.js
  src/const.js
  src/containers/header-slide-title.js
  src/layer/data/_types.js
  src/navigator/index.js
  src/screens/lesson.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  src/types.js
Labels: pr: :rocket: New feature

#89 Change implementation of editAnswer and validateAnswer
  __e2e__/lives.test.js
  package.json
  src/containers/header-slide-right.js
  src/screens/correction.js
  src/screens/question.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI, pr: :wrench: Refactoring

#96 Add cache for detox-cli and iOS e2e builds
  .circleci/config.yml
  package.json
Labels: pr: :lollipop: Enhancement

#97 Prepare deployment in parallel to builds to speed up workflow
  .circleci/config.yml
Labels: pr: :wrench: Refactoring

#81 Clue final
  __e2e__/clue.test.js
  flow-typed/npm/react-navigation_v3.x.x.js
  package.json
  scripts/pull-translations.js
  src/__fixtures__/discipline-bundle/no-clue.js
  src/__fixtures__/slides.js
  src/components/__snapshots__/clue-front-item.stories.storyshot
  src/components/__snapshots__/clue.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/slide-header.stories.storyshot
  src/components/__snapshots__/slide.stories.storyshot
  src/components/__snapshots__/theme-provider.stories.storyshot
  src/components/clue-front-item.js
  src/components/clue-front-item.stories.js
  src/components/clue.js
  src/components/clue.stories.js
  src/containers/card-flippable.js
  src/containers/network-info-listener.js
  src/containers/tab-bar-slide.js
  src/layer/data/_types.js
  src/layer/data/clues.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/layer/data/mappers.js
  src/layer/data/mappers.test.js
  src/navigator/slide.js
  src/screens/clue.js
  src/stories.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  yarn.lock
Labels: pr: :rocket: New feature

#70 Lesson PDF
  .circleci/config.yml
  __e2e__/lesson.test.js
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  ios/Coorpacademy.xcodeproj/project.pbxproj
  jest-setup.js
  jest.config.e2e.js
  jest.config.unit.js
  package.json
  src/app.js
  src/components/__snapshots__/button.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/clue-front-item.stories.storyshot
  src/components/__snapshots__/clue.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/pdf.stories.storyshot
  src/components/__snapshots__/preview.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/button.js
  src/components/catalog.stories.js
  src/components/home.stories.js
  src/components/lesson.js
  src/components/lesson.stories.js
  src/components/pdf.js
  src/components/pdf.stories.js
  src/components/preview.js
  src/components/question-choices.stories.js
  src/index.android.js
  src/index.js
  src/modules/environment.test.js
  src/modules/image.test.js
  src/modules/uri.test.js
  src/navigator/index.js
  src/navigator/pdf.js
  src/screens/lesson.js
  src/screens/pdf.js
  src/stories.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :rocket: New feature

#98 add bescherelle course
  package.json
  src/__fixtures__/bescherelle-course/chapters.js
  src/__fixtures__/bescherelle-course/discipline.js
  src/__fixtures__/bescherelle-course/exit-nodes.js
  src/__fixtures__/bescherelle-course/index.js
  src/__fixtures__/bescherelle-course/slides.js
  src/containers/network-info-listener.js
  src/layer/data/_types.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/screens/home.js
  yarn.lock
Labels: pr: :rocket: New feature

#100 Fix PP and remove cache on pods
  .circleci/config.yml
  ios/Coorpacademy.xcodeproj/project.pbxproj
Labels: pr: :construction: Work In Progress

#109 Add version to open app to testerrs
  .circleci/config.yml
  scripts/pull-translations.js
  src/components/__snapshots__/home.stories.storyshot
  src/components/home.js
  src/components/home.stories.js
  src/modules/version.json
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/index.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
Labels: pr: :rocket: New feature

#117 Fix stuck steps in CI
  .circleci/config.yml
Labels: pr: :soon: Waiting for CI, pr: :wrench: Refactoring

#119 New devices on Apple developer console
  .circleci/config.yml
  ios/Coorpacademy.xcodeproj/project.pbxproj
Labels: pr: :wrench: Refactoring

#113 Feature/test map state to props
  package.json
  src/__fixtures__/progression.js
  src/__fixtures__/questions.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/__fixtures__/utils/mappers.js
  src/__fixtures__/utils/mappers.test.js
  src/containers/header-slide-title.js
  src/containers/header-slide-title.test.js
  src/layer/data/_types.js
  src/layer/data/mappers.js
  src/redux/reducers/discipline-bundle.js
  src/redux/store.js
  src/screens/lesson.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature, pr: :soon: Waiting for CI

#111 Resources browser
  .circleci/config.yml
  __e2e__/lesson.test.js
  flow-typed/npm/react-navigation_v3.x.x.js
  package.json
  scripts/pull-translations.js
  src/__fixtures__/discipline-bundle/adaptive.js
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/discipline-bundle/no-clue.js
  src/__fixtures__/lessons.js
  src/__fixtures__/slides.js
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/html.js
  src/components/lesson.js
  src/components/lesson.stories.js
  src/components/preview.stories.js
  src/components/resource.js
  src/components/resource.stories.js
  src/components/resources-browser.js
  src/components/resources-browser.stories.js
  src/containers/tab-bar-slide.js
  src/screens/lesson.js
  src/stories.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  yarn.lock
Labels: pr: :rocket: New feature, pr: :soon: Waiting for CI

#102 Add video subtitles
  __e2e__/lesson.test.js
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/assets/empty.vtt
  jest-setup.js
  jest.config.unit.js
  package.json
  rn-cli.config.js
  src/__fixtures__/lessons.js
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/__snapshots__/video.stories.storyshot
  src/components/brand-theme-provider.js
  src/components/lesson.js
  src/components/resource.js
  src/components/video.js
  src/components/video.stories.js
  src/containers/video-controlable.js
  src/layer/data/mappers.js
  src/modules/subtitles.e2e.js
  src/modules/subtitles.js
  src/modules/subtitles.test.js
  yarn.lock
Labels: pr: :rocket: New feature, pr: :soon: Waiting for CI

#116 Cards fetch at start
  __e2e__/lives.test.js
  __e2e__/progression.test.js
  src/__fixtures__/__temporary__/bescherelle-course/chapters.js
  src/__fixtures__/__temporary__/bescherelle-course/discipline.js
  src/__fixtures__/__temporary__/bescherelle-course/exit-nodes.js
  src/__fixtures__/__temporary__/bescherelle-course/index.js
  src/__fixtures__/__temporary__/bescherelle-course/slides.js
  src/__fixtures__/__temporary__/cards.js
  src/__fixtures__/__temporary__/onboarding-course/chapters.js
  src/__fixtures__/__temporary__/onboarding-course/discipline.js
  src/__fixtures__/__temporary__/onboarding-course/exit-nodes.js
  src/__fixtures__/__temporary__/onboarding-course/index.js
  src/__fixtures__/__temporary__/onboarding-course/slides.js
  src/__fixtures__/cards.js
  src/__fixtures__/discipline-bundle/adaptive.js
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/lessons.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/cards.stories.js
  src/components/catalog.js
  src/components/catalog.stories.js
  src/components/home.js
  src/components/home.stories.js
  src/components/lesson.stories.js
  src/containers/catalog.js
  src/containers/network-info-listener.js
  src/layer/data/_const.js
  src/layer/data/_types.js
  src/layer/data/cards.js
  src/layer/data/cards.test.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/layer/data/index.js
  src/layer/data/mappers.test.js
  src/layer/data/slides.test.js
  src/redux/actions/cards.js
  src/redux/actions/cards.test.js
  src/redux/actions/discipline-bundle.js
  src/redux/actions/discipline-bundle.test.js
  src/redux/middlewares/cards.js
  src/redux/middlewares/cards.test.js
  src/redux/middlewares/discipline-bundle.js
  src/redux/middlewares/discipline-bundle.test.js
  src/redux/reducers/cards.js
  src/redux/reducers/cards.test.js
  src/redux/reducers/discipline-bundle.test.js
  src/redux/store.js
  src/screens/home.js
  src/services/cards.js
  src/services/discipline-bundle.js
  src/services/index.js
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring

#123 Reduce padding for slides title
  src/components/__snapshots__/clue.stories.storyshot
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/clue.js
  src/components/context.js
  src/components/lesson.js
  src/components/question.js
Labels: pr: :lollipop: Enhancement

#124 Use the fresh new VTT endpoint (subtitles)
  src/__fixtures__/discipline-bundle/adaptive.js
  src/__fixtures__/discipline-bundle/basic.js
  src/components/__snapshots__/video.stories.storyshot
  src/components/brand-theme-provider.js
  src/components/lesson.js
  src/components/video.stories.js
  src/modules/subtitles.e2e.js
  src/modules/subtitles.js
  src/modules/subtitles.test.js
Labels: pr: :lollipop: Enhancement

#127 Change UI for selected resource in browser
  __e2e__/lesson.test.js
  src/__fixtures__/__temporary__/onboarding-course/slides.js
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/resource-overlay.js
  src/components/resources-browser.js
Labels: pr: :lollipop: Enhancement

#128 Deploy on AWS EC2 instead of Heroku
  .circleci/adhoc-template.plist
  .circleci/config.yml
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring
