Repository CoorpAcademy/mobile, pull requests merged in 2019-09, with the labels that each got.

#403 Add haptic feedbacks on touchable things (buttons, area)
  android/app/build.gradle
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  flow-typed/npm/react-navigation_v3.x.x.js
  ios/Podfile
  ios/Podfile.lock
  jest-setup.js
  jest.config.unit.js
  package.json
  src/components/__snapshots__/authentication-details.stories.storyshot
  src/components/__snapshots__/authentication-footer.stories.storyshot
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/button-sticky.js
  src/components/button.js
  src/components/button.stories.js
  src/components/cards.js
  src/components/cards.stories.js
  src/components/correction.js
  src/components/correction.stories.js
  src/components/html.js
  src/components/html.stories.js
  src/components/level-end.js
  src/components/level-end.stories.js
  src/components/touchable.js
  src/components/touchable.stories.js
  src/containers/cards-swipable.js
  src/containers/header-left.js
  src/containers/tab-bar.js
  src/containers/with-audio.js
  src/containers/with-audio.test.js
  src/containers/with-vibration.js
  src/containers/with-vibration.test.js
  src/modules/audio-player.js
  src/navigator/navigation-options.js
  src/screens/correction.js
  src/screens/level-end.js
  src/screens/level-end.test.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :bulb: POC, pr: :lollipop: Enhancement

#406 Fix automatic tab switch when user is not on Question or Context
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/containers/tab-bar-slide.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
Labels: pr: :bug: Bug Fix

#405 Dynamic links
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/build.gradle
  ios/Coorpacademy-tvOS/Info.plist
  ios/Coorpacademy-tvOSTests/Info.plist
  ios/Coorpacademy/AppDelegate.m
  ios/Coorpacademy/Coorpacademy.entitlements
  ios/Coorpacademy/Info.plist
  ios/CoorpacademyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/containers/with-universal-links.js
  src/types.js
Labels: pr: :rocket: New feature

#407 Apply pixel ratio to resized images
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/header-slide-title.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/image-background.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/image-background.stories.js
  src/modules/image.js
  src/modules/image.test.js
Labels: pr: :lollipop: Enhancement

#414 Fix godmode and fastslide enabled for everyone
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/__fixtures__/tokens.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/redux/actions/brands.test.js
  src/redux/actions/catalog/cards/fetch.test.js
  src/redux/actions/catalog/cards/refresh.test.js
  src/redux/actions/fast-slide.js
  src/redux/actions/fast-slide.test.js
  src/redux/actions/god-mode.js
  src/redux/actions/god-mode.test.js
  src/redux/actions/progressions/synchronize.test.js
  src/redux/middlewares/progressions-synchronization.test.js
  src/redux/middlewares/reset-displayed-progression.test.js
  src/redux/reducers/authentication/token.js
  src/redux/reducers/authentication/token.test.js
  src/redux/utils/has-role.js
  src/redux/utils/has-role.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
Labels: pr: :bug: Bug Fix

#413 Increase the coverage on models and utils folders
  jest.config.unit.js
  src/models/error.js
  src/utils/local-token.test.js
Labels: pr: :white_check_mark: Enhance tests

#408 Memoize and unit tests on screens mapStateToProps
  flow-typed/npm/reselect_v4.x.x.js
  jest.config.unit.js
  src/__fixtures__/engine-config.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/__fixtures__/utils/mappers.js
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-slider.stories.storyshot
  src/components/brand-theme-provider.js
  src/components/correction.stories.js
  src/components/lesson.stories.js
  src/components/question-choices.js
  src/components/question-choices.stories.js
  src/components/question-slider.js
  src/components/question-slider.stories.js
  src/components/question.js
  src/components/resource.stories.js
  src/components/resources-browser.stories.js
  src/containers/catalog-section-refreshable.js
  src/containers/catalog.js
  src/containers/question-slider.js
  src/containers/question-slider.test.js
  src/layer/data/mappers.js
  src/layer/data/mappers.test.js
  src/modules/store.js
  src/modules/store.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/screens/authentication.js
  src/screens/authentication.test.js
  src/screens/clue.js
  src/screens/clue.test.js
  src/screens/context.js
  src/screens/context.test.js
  src/screens/correction.js
  src/screens/correction.test.js
  src/screens/home.js
  src/screens/home.test.js
  src/screens/lesson.js
  src/screens/lesson.test.js
  src/screens/level-end.js
  src/screens/qr-code.js
  src/screens/qr-code.test.js
  src/screens/question.js
  src/screens/question.test.js
Labels: pr: :white_check_mark: Enhance tests, pr: :wrench: Refactoring

#417 React.useContext(JustForFC)
  src/components/catalog-item-badge.js
  src/components/header-slide-title.js
  src/components/home.js
  src/components/progression.js
  src/components/question-choice.js
  src/components/question-slider.js
  src/containers/with-analytics.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#418 Add unit tests for AuthenticationDetails screen
  jest-setup.js
  jest.config.unit.js
  src/__fixtures__/navigation.js
  src/screens/authentication-details.test.js
Labels: pr: :white_check_mark: Enhance tests

#419 Hero redux
  jest.config.unit.js
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/components/catalog.stories.js
  src/containers/catalog-section-refreshable.test.js
  src/containers/catalog.js
  src/containers/catalog.test.js
  src/redux/actions/catalog/hero.js
  src/redux/actions/catalog/hero.test.js
  src/redux/actions/progressions/create-chapter-progression.test.js
  src/redux/actions/progressions/create-level-progression.test.js
  src/redux/reducers/catalog.js
  src/redux/reducers/catalog.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/screens/level-end.test.js
  src/services/hero.js
  src/services/hero.test.js
  src/services/index.js
Labels: pr: :rocket: New feature

#422 Fix / describe bluetooth usage
  ios/Coorpacademy/Info.plist
Labels: pr: :bug: Bug Fix

#423 Bump the screen coverage to 100%
  .circleci/config.yml
  app.json
  jest-setup.js
  jest.config.unit.js
  package.json
  src/__fixtures__/navigation.js
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/qr-code-scanner.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/authentication.js
  src/components/context.js
  src/components/correction.js
  src/components/home.js
  src/components/html.js
  src/components/lesson.js
  src/components/level-end.js
  src/components/qr-code-scanner.js
  src/components/question.js
  src/containers/__mocks__/with-audio.js
  src/containers/__mocks__/with-vibration.js
  src/containers/error-listener.js
  src/containers/with-audio.js
  src/containers/with-audio.test.js
  src/containers/with-vibration.test.js
  src/modules/environment.js
  src/redux/actions/clues.js
  src/redux/actions/clues.test.js
  src/screens/authentication-details.test.js
  src/screens/authentication.js
  src/screens/authentication.test.js
  src/screens/browser.js
  src/screens/browser.test.js
  src/screens/clue.js
  src/screens/clue.test.js
  src/screens/context.js
  src/screens/context.test.js
  src/screens/correction.js
  src/screens/correction.test.js
  src/screens/home.js
  src/screens/home.test.js
  src/screens/lesson.js
  src/screens/lesson.test.js
  src/screens/level-end.js
  src/screens/level-end.test.js
  src/screens/pdf.js
  src/screens/pdf.test.js
  src/screens/qr-code.js
  src/screens/qr-code.test.js
  src/screens/question.js
  src/screens/question.test.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :white_check_mark: Enhance tests

#424 Link watchman dependencies to avoid errors
  .circleci/config.yml
Labels: pr: :soon: Waiting for CI
