Repository CoorpAcademy/mobile, pull requests merged in 2019-11, with the labels that each got.

#437 Fixing Correction Screen Error Answers
  src/components/cards.js
  src/components/correction.js
Labels: pr: :bug: Bug Fix, pr: :mag_right: Need functional review

#440 Use node version specified in .nvmrc for android docker CI steps
  .circleci/config.yml
Labels: pr: :wrench: Refactoring

#441 Enable sync progression retry even after finishing a level(MVP)
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/redux/middlewares/progressions-synchronization.js
  src/redux/middlewares/progressions-synchronization.test.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#443 Add more sync progression listener and rework of the recursive sync progression function
  src/redux/actions/progressions/synchronize.js
  src/redux/middlewares/progressions-synchronization.js
  src/redux/middlewares/progressions-synchronization.test.js
Labels: pr: :lollipop: Enhancement

#444 Delay progression sync
  package.json
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  yarn.lock
Labels: pr: :lollipop: Enhancement

#442 integrating new select-progression
  package.json
  yarn.lock
Labels: pr: :lollipop: Enhancement

#446 Migrate to AndroidX
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/app/src/main/java/com/coorpacademy/app/SplashActivity.java
  android/build.gradle
  android/gradle.properties
  package.json
  yarn.lock
Labels: pr: :mag_right: Need functional review, pr: :no_entry: Do not merge

#445 Connection listener offline
  android/app/build.gradle
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  flow-typed/npm/@react-native-community/netinfo_v4.x.x.js
  flow-typed/npm/react-native-offline_v5.x.x.js
  ios/Podfile
  ios/Podfile.lock
  metro.config.js
  package.json
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/app.js
  src/redux/middlewares/progressions-synchronization.js
  src/redux/middlewares/progressions-synchronization.test.js
  src/redux/store.js
  yarn.lock
Labels: pr: :rocket: New feature

#438 Upgrade node@10, Xcode@11.2.1, build gems and watchman config
  .circleci/config.yml
  .github/INSTALLATION.md
  .nvmrc
  .watchmanconfig
  .xcoderc
  android/Gemfile
  android/Gemfile.lock
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: pr: :mag_right: Need functional review, pr: 🔭💻 R&D

#449 Fix/sync progression (403 & 409)
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/models/error.js
  src/models/error.test.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/utils/tests.js
Labels: pr: :bug: Bug Fix

#447 Add in-app notification to notify a lost/restored connection
  jest-setup.js
  jest.config.unit.js
  package.json
  scripts/pull-translations.js
  src/app.js
  src/containers/connection-listener.js
  src/containers/connection-listener.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  yarn.lock
Labels: pr: :no_entry: Do not merge, pr: :page_facing_up: Waiting for translations, pr: :rocket: New feature, pr: 🔭💻 R&D

#451 Fix non-valide response type
  src/modules/fetch.js
  src/screens/question.js
  src/screens/question.test.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
