Repository CoorpAcademy/mobile, pull requests merged in 2019-04, with the labels that each got.

#237 Bump to 1.1.7
  android/app/build.gradle
  ios/Coorpacademy-tvOS/Info.plist
  ios/Coorpacademy-tvOSTests/Info.plist
  ios/Coorpacademy/Info.plist
  ios/CoorpacademyTests/Info.plist
  package.json
Labels: pr: :soon: Waiting for CI

#229 Bugfix video playing background
  jest-setup.js
  package.json
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/context.js
  src/containers/video-controlable.js
  src/layer/data/cards.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#239 Cleanup legacy data
  jest.config.unit.js
  src/layer/data/base/dis_V1uaa8qIV-fr.json
  src/layer/data/base/exitnodes.json
  src/layer/data/base/index.js
  src/layer/data/base/levels.json
Labels: pr: :wrench: Refactoring

#238 Fix infinite splashscreen on Storybook
  README.md
  index.js
  package.json
  src/modules/environment.js
  src/modules/environment.test.js
  storybook/index.js
  storybook/stories/components/welcome.js
Labels: pr: :bug: Bug Fix, pr: :collision: Breaking Change!, pr: :lollipop: Enhancement

#236 change space between logo and text on login page
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/authentication.js
Labels: pr: :soon: Waiting for CI

#241 Use podfile for iOS dependencies
  .circleci/config.yml
  README.md
  android/Gemfile.lock
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/fastlane/Fastfile
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/fastlane/Fastfile
  package.json
  yarn.lock
Labels: pr: :wrench: Refactoring

#199 Parallelism
  .circleci/config.yml
  .gitignore
  jest.config.e2e.js
  jest.config.unit.js
  package.json
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#243 Fix auto bump
  .circleci/config.yml
Labels: pr: :bug: Bug Fix

#242 bump translations
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/tooltip.stories.storyshot
  src/components/level-end.js
  src/components/level-end.stories.js
  src/components/tooltip.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/translations/cs.js
  src/translations/fr.js
  src/translations/ru.js
  src/translations/uk.js
  src/translations/zh-tw.js
Labels: pr: :no_entry: Do not merge

#244 Fix publish and infinite loop on auto bump
  .circleci/config.yml
Labels: pr: :bug: Bug Fix

#245 Try to publish again and again
  .circleci/config.yml
Labels: pr: :bug: Bug Fix

#251 Add screens tracking and ability to track events
  .circleci/config.yml
  .gitignore
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugUnitTestRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseRuntimeClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/releaseUnitTestRuntimeClasspath.lockfile
  android/app/proguard-rules.pro
  android/app/src/main/assets/containers/GTM-TFRSV62.json
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/build.gradle
  android/settings.gradle
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Coorpacademy.xcodeproj/xcshareddata/xcschemes/Coorpacademy.xcscheme
  ios/Coorpacademy/AppDelegate.m
  ios/Coorpacademy/Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/container/GTM-KVTSSJK.json
  jest-setup.js
  jest.config.unit.js
  package.json
  scripts/pull-firebase-config.js
  src/app.js
  src/components/button.js
  src/layer/data/analytics.js
  src/layer/data/analytics.test.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/modules/template.test.js
  src/navigator/index.js
  src/navigator/navigation-options.js
  src/redux/actions/navigation.js
  src/redux/actions/navigation.test.js
  src/redux/index.js
  src/redux/reducers/navigation.js
  src/services/analytics.js
  src/services/analytics.test.js
  src/services/index.js
  src/services/progressions.js
  src/services/progressions.test.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :no_entry: Do not merge, pr: :rocket: New feature

#253 anonymous signIn done✓
  scripts/pull-translations.js
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/authentication.js
  src/components/authentication.stories.js
  src/components/html.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/screens/authentication.js
  src/screens/home.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
Labels: pr: :rocket: New feature

#257 fix padding auth and center demo text
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/authentication.js
  src/containers/carousel.js
Labels: pr: :bug: Bug Fix, pr: :soon: Waiting for CI

#258 Update confettis animation lib
  package.json
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/level-end.js
  src/components/level-end.stories.js
  src/screens/level-end.js
  yarn.lock
Labels: pr: :bug: Bug Fix

#261 Update @coorpacademy-xxxx packages
  package.json
  scripts/pull-certificate-android.js
  src/__fixtures__/progression.js
  src/components/card-header.js
  src/components/correction.js
  src/components/lives.js
  src/containers/carousel.js
  src/containers/network-info-listener.js
  src/containers/tab-bar-slide.js
  src/containers/video-controlable.js
  src/containers/with-permissions.js
  src/layer/data/_const.js
  src/layer/data/brand.test.js
  src/layer/data/cards.js
  src/layer/data/progressions.js
  src/navigator/index.js
  src/redux/actions/progression.js
  src/screens/authentication.js
  src/screens/clue.js
  src/screens/context.js
  src/screens/correction.js
  src/screens/home.js
  src/screens/lesson.js
  src/screens/level-end.js
  src/screens/question.js
  src/screens/splash.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#259 Swipes
  src/__fixtures__/lessons.js
  src/components/cards.js
  src/components/cards.stories.js
  src/components/correction.js
  src/components/level-end.js
  src/const.js
  src/containers/cards-scalable.js
  src/containers/cards-scalable.test.js
  src/containers/carousel.js
  src/types.js
Labels: pr: :rocket: New feature, pr: :soon: Waiting for CI

#266 Add documentation after Xcode upgrade
  .github/TROUBLESHOOTING.md
  android/app/build.gradle
  android/app/gradle/dependency-locks/debugAndroidTestCompileClasspath.lockfile
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/src/androidTest/java/com/coorpacademy/app/DetoxTest.java
Labels: pr: :memo: Documentation, pr: :wrench: Refactoring

#267 Set firebase debug on debug, adhoc but not in release
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Coorpacademy.xcodeproj/xcshareddata/xcschemes/Coorpacademy.xcscheme
  ios/Coorpacademy/AppDelegate.m
  ios/Coorpacademy/Info.plist
  ios/config/adhoc.xcconfig
  ios/config/debug.xcconfig
  ios/config/release.xcconfig
  ios/fastlane/Fastfile
Labels: pr: :rocket: New feature

#268 Tracking documentation and hit on answer
  .github/FIREBASE.md
  README.md
  jest.config.unit.js
  src/const.js
  src/redux/actions/ui/answers.js
  src/redux/actions/ui/answers.test.js
  src/screens/question.js
  src/types.js
Labels: pr: :memo: Documentation, pr: :rocket: New feature, pr: :soon: Waiting for CI

#262 Simplify sign in/out and log events on this
  .circleci/config.yml
  src/app.js
  src/components/analytics-provider.stories.js
  src/const.js
  src/containers/network-info-listener.js
  src/layer/data/analytics.js
  src/layer/data/analytics.test.js
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/navigator/index.js
  src/navigator/navigation-options.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/redux/actions/brands.js
  src/redux/actions/brands.test.js
  src/redux/actions/navigation.js
  src/redux/actions/navigation.test.js
  src/redux/reducers/navigation.js
  src/screens/authentication.js
  src/screens/home.js
  src/services/analytics.js
  src/services/analytics.test.js
  src/types.js
  src/utils/tests.js
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring

#270 Add deeplink schemes
  README.md
  android/app/src/main/AndroidManifest.xml
  ios/Coorpacademy/AppDelegate.m
  ios/Coorpacademy/Info.plist
  src/navigator/index.js
  src/navigator/navigation-options.js
  src/redux/actions/authentication.js
  src/redux/actions/authentication.test.js
  src/redux/reducers/navigation.test.js
  src/screens/authentication.js
  src/screens/home.js
  src/screens/splash.js
  src/types.js
Labels: pr: :rocket: New feature

#276 Add Xcode locked version
  .xcoderc
  ios/fastlane/Fastfile
  package.json
  yarn.lock
Labels: pr: :rocket: New feature
