Repository CoorpAcademy/mobile, pull requests merged in 2019-08, with the labels that each got.

#387 Default learner engine version to 2
  package.json
  yarn.lock
Labels: pr: :collision: Breaking Change!, pr: :lollipop: Enhancement

#390 Infinite lives in microlearning player (v2 engine)
  __e2e__/lives.test.js
  __e2e__/microlearning.test.js
  package.json
  src/redux/actions/progressions/create-chapter-progression.js
  src/redux/actions/progressions/create-chapter-progression.test.js
  src/redux/actions/progressions/create-next-progressions.test.js
  yarn.lock
Labels: pr: :rocket: New feature

#391 Use only one component for images and use media API to resize them
  __e2e__/context.test.js
  __e2e__/correction.resources.test.js
  __e2e__/lesson.test.js
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/brand-theme-provider.stories.storyshot
  src/components/__snapshots__/button-sticky.stories.storyshot
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-slide-title.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/image-background.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/preview.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/__snapshots__/video.stories.storyshot
  src/components/authentication.js
  src/components/brand-theme-provider.stories.js
  src/components/button-sticky.stories.js
  src/components/card.stories.js
  src/components/catalog-item.js
  src/components/catalog-item.stories.js
  src/components/catalog-section.js
  src/components/catalog.stories.js
  src/components/correction.js
  src/components/correction.stories.js
  src/components/header-slide-title.js
  src/components/header-slide-title.stories.js
  src/components/home.js
  src/components/image-background.js
  src/components/image-background.stories.js
  src/components/image-gradient.js
  src/components/image-gradient.stories.js
  src/components/image.js
  src/components/image.stories.js
  src/components/preview.js
  src/components/resource.js
  src/components/resource.stories.js
  src/components/resources-browser.js
  src/containers/header-slide-title.js
  src/modules/image.js
  src/modules/image.test.js
  src/stories.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#395 Increase performance
  babel.config.js
  flow-typed/_custom-defs.js
  package.json
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/catalog-section.js
  src/components/catalog.js
  src/components/catalog.stories.js
  src/containers/cards-swipable.test.js
  src/containers/catalog-section-refreshable.js
  src/containers/catalog-section-refreshable.test.js
  src/containers/catalog.js
  src/containers/catalog.test.js
  src/containers/header-slide-title.test.js
  src/containers/question-slider.test.js
  src/modules/equal.js
  src/modules/equal.test.js
  src/screens/level-end.test.js
  src/utils/tests.js
  yarn.lock
Labels: pr: :construction: Work In Progress, pr: :lollipop: Enhancement

#400 Fix completion at back to home
  src/containers/catalog-section-refreshable.js
  src/layer/data/cards.js
Labels: pr: :bug: Bug Fix
