Repository CoorpAcademy/mobile, pull requests merged in 2019-03, with the labels that each got.

#133 Question template
  __e2e__/questions.test.js
  __e2e__/template.test.js
  package.json
  scripts/pull-translations.js
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/discipline-bundle/index.js
  src/__fixtures__/discipline-bundle/template.js
  src/__fixtures__/question-choices.js
  src/__fixtures__/questions.js
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-input.stories.storyshot
  src/components/__snapshots__/question-template.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/select.stories.storyshot
  src/components/question-choices.js
  src/components/question-choices.stories.js
  src/components/question-input.js
  src/components/question-input.stories.js
  src/components/question-template.js
  src/components/question-template.stories.js
  src/components/question.js
  src/components/question.stories.js
  src/components/select.js
  src/components/select.stories.js
  src/const.js
  src/layer/data/cards.js
  src/layer/data/cards.test.js
  src/layer/data/core.js
  src/layer/data/core.test.js
  src/modules/template.js
  src/modules/template.test.js
  src/screens/question.js
  src/stories.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  src/types.js
  yarn.lock
Labels: pr: :rocket: New feature

#131 Resource viewed action
  package.json
  src/__fixtures__/__temporary__/bescherelle-course/slides.js
  src/__fixtures__/__temporary__/onboarding-course/slides.js
  src/__fixtures__/lessons.js
  src/__fixtures__/slides.js
  src/__fixtures__/utils/mappers.js
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resources-browser.stories.storyshot
  src/components/lesson.js
  src/components/resources-browser.js
  src/containers/video-controlable.js
  src/layer/data/_types.js
  src/layer/data/mappers.js
  src/layer/data/mappers.test.js
  src/screens/lesson.js
  src/services/analytics.js
  src/services/index.js
  yarn.lock
Labels: pr: :lollipop: Enhancement

#132 Question Draggable Feature
  __e2e__/questions.test.js
  scripts/pull-translations.js
  src/__fixtures__/discipline-bundle/index.js
  src/__fixtures__/discipline-bundle/with-qcm-drag.js
  src/__fixtures__/questions.js
  src/components/__snapshots__/drop-zone.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-draggable.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/drop-zone.js
  src/components/drop-zone.stories.js
  src/components/question-choice.js
  src/components/question-choices.js
  src/components/question-choices.stories.js
  src/components/question-draggable.js
  src/components/question-draggable.stories.js
  src/components/question-draggable.test.js
  src/components/question.stories.js
  src/const.js
  src/screens/question.js
  src/stories.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  src/types.js
  yarn.lock
Labels: pr: :rocket: New feature

#137 Basic question
  __e2e__/context.test.js
  __e2e__/question-basic.test.js
  __e2e__/question-template.test.js
  package.json
  src/__fixtures__/discipline-bundle/index.js
  src/__fixtures__/discipline-bundle/with-question-basic.js
  src/__fixtures__/questions.js
  src/components/__snapshots__/question-basic.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-input.stories.storyshot
  src/components/__snapshots__/question-template.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/question-choices.js
  src/components/question-choices.stories.js
  src/components/question-draggable.test.js
  src/components/question-input.js
  src/components/question-input.stories.js
  src/components/question.js
  src/components/question.stories.js
  src/const.js
  src/screens/question.js
  yarn.lock
Labels: pr: :rocket: New feature

#145 Question Choice for Graphic Question Rework
  __e2e__/lives.test.js
  __e2e__/question-draggable.test.js
  __e2e__/questions.test.js
  src/components/__snapshots__/drop-zone.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-draggable.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/drop-zone.js
  src/components/drop-zone.stories.js
  src/components/question-choice.js
  src/components/question-choice.stories.js
  src/components/question-choices.js
  src/components/question-draggable.js
  src/components/question-draggable.stories.js
  src/containers/image-background-scalable.js
Labels: pr: :lollipop: Enhancement

#156 fix qcm graph
  src/__fixtures__/cards.js
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/drop-zone.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-draggable.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/question-choice.js
  src/containers/image-background-scalable.js
Labels: pr: :lollipop: Enhancement

#170 Fix unit tests and some dependencies
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/gradient.stories.storyshot
  src/components/__snapshots__/image-gradient.stories.storyshot
  src/components/authentication.js
  src/components/gradient.js
  src/components/gradient.stories.js
  src/components/image-gradient.js
  src/containers/card-scalable.js
  src/containers/splash-screen.js
Labels: pr: :wrench: Refactoring

#159 Configure Automation to build and publish Application
  .circleci/config.yml
  .gitignore
  android/Gemfile.lock
  android/app/gradle/dependency-locks/debugAndroidTestRuntimeClasspath.lockfile
  android/app/src/main/AndroidManifest.xml
  android/app/src/release/AndroidManifest.xml
  android/build.gradle
  android/fastlane/.env
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-1024.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-152.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-167.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-20@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-20@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-29@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-29@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-40@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-40@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-60@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-60@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-76.png
  ios/Coorpacademy/Images.xcassets/Contents.json
  ios/Coorpacademy/Info.plist
  ios/Gemfile.lock
  ios/fastlane/Fastfile
  ios/fastlane/Pluginfile
  ios/release/Coorpacademy.ipa
  ios/release/Coorpacademy.plist
  ios/release/index.html
  jest.config.unit.js
  package.json
  scripts/generate-assets.js
  scripts/pull-certificate-android.js
  scripts/update-version.js
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/catalog.js
  src/modules/environment.js
  src/modules/version.json
  src/modules/version.unit.json
  src/screens/qr-code.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#173 Add documentation for config.h error
  .github/TROUBLESHOOTING.md
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#172 Pagination mocked to avoid snapshot issues
  jest-setup.js
  src/components/__snapshots__/authentication.stories.storyshot
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#174 Fix gradient on home without height
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/gradient.stories.storyshot
  src/components/__snapshots__/image-gradient.stories.storyshot
  src/components/gradient.js
Labels: pr: :bug: Bug Fix

#166 Add documentation to renew adhoc PP
  .github/FASTLANE.md
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#168 Run e2e tests only if linting and unit tests are fine
  .circleci/config.yml
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#177 Force upgrade once app version is under minimum version maintained
  jest.config.unit.js
  package.json
  scripts/pull-translations.js
  scripts/update-version.js
  src/app.js
  src/components/__snapshots__/splash.stories.storyshot
  src/components/authentication.js
  src/components/splash.js
  src/components/splash.stories.js
  src/containers/version-listener.js
  src/modules/store.js
  src/modules/store.test.js
  src/modules/version.unit.json
  src/screens/authentication.js
  src/screens/splash.js
  src/stories.js
  src/translations/_types.js
  src/translations/cs.js
  src/translations/de.js
  src/translations/en-us.js
  src/translations/en.js
  src/translations/es.js
  src/translations/fr.js
  src/translations/hu.js
  src/translations/it.js
  src/translations/ja.js
  src/translations/ko.js
  src/translations/nl.js
  src/translations/pl.js
  src/translations/pt.js
  src/translations/ro.js
  src/translations/ru.js
  src/translations/tr.js
  src/translations/uk.js
  src/translations/vi.js
  src/translations/zh-tw.js
  src/translations/zh.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :rocket: New feature

#182 Fixes: lives overflow, disabled tabs label position, gestures in modals & safe areas
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-slide-right.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/lives.stories.storyshot
  src/components/__snapshots__/splash.stories.storyshot
  src/components/__snapshots__/version.stories.storyshot
  src/components/authentication.js
  src/components/catalog.js
  src/components/home.js
  src/components/lives.js
  src/components/splash.js
  src/components/version.js
  src/components/version.stories.js
  src/containers/lives-animated.js
  src/containers/tab-bar-slide.js
  src/navigator/index.js
  src/navigator/navigation-options.js
  src/navigator/slide.js
  src/stories.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#186 Add an automatic workflow to publish-to-store :rocket:
  .circleci/config.yml
Labels: pr: :rocket: New feature

#184 Fix potential undefined value
  src/components/lesson.js
Labels: pr: :bug: Bug Fix

#190 New dock icon
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-1024.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-152.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-167.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-20@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-20@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-29@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-29@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-40@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-40@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-60@2x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-60@3x.png
  ios/Coorpacademy/Images.xcassets/AppIcon.appiconset/icon-dock-76.png
  scripts/generate-assets.js
  src/assets/images/dock-icon-background.png
  src/assets/images/dock-icon-foreground.png
  src/assets/images/dock-icon.png
Labels: pr: :lollipop: Enhancement

#194 Fix bug retry
  src/screens/correction.js
Labels: pr: :bug: Bug Fix, pr: :soon: Waiting for CI

#195 Fix lesson padding on bottom
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/lesson.js
Labels: pr: :bug: Bug Fix

#183 Lesson notification
  __e2e__/lesson.test.js
  src/components/__snapshots__/notification.stories.storyshot
  src/components/notification.js
  src/components/notification.stories.js
  src/containers/notification-animated.js
  src/containers/tab-bar-slide.js
  src/modules/theme.js
  src/navigator/slide.js
  src/stories.js
Labels: pr: :rocket: New feature, pr: :soon: Waiting for CI

#193 Clear on logout
  .eslintrc
  __e2e__/utils.js
  flow-typed/semver-compare.js
  src/__fixtures__/brands.js
  src/const.js
  src/layer/data/_const.js
  src/layer/data/mappers.test.js
  src/modules/image.js
  src/modules/store.js
  src/modules/version.js.flow
  src/redux/actions/authentication.js
  src/redux/actions/cards.js
  src/redux/actions/discipline-bundle.js
  src/redux/actions/navigation.js
  src/redux/actions/permissions.js
  src/redux/actions/progression.js
  src/redux/store.js
  src/redux/utils/reset-on-logout.js
  src/redux/utils/reset-on-logout.test.js
  src/utils/content.js
  src/utils/tests.js
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI, pr: :wrench: Refactoring

#198 Starburst - bottom gradient
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/starburst.stories.storyshot
  src/components/level-end.js
  src/components/starburst.js
  src/components/starburst.stories.js
Labels: pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#206 Fixes the cards order at mount
  src/screens/correction.js
Labels: pr: :bug: Bug Fix

#214 Notifying publications to slack
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
  package.json
  scripts/notify-publication.js
  yarn.lock
Labels: pr: :rocket: New feature

#205 Manage status bar everywhere
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/coorpacademy/app/MainActivity.java
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  src/__fixtures__/context.js
  src/components/brand-theme-provider.js
  src/components/catalog-item-footer.js
  src/components/progression-bar.js
  src/layer/data/core.js
  src/navigator/index.js
  src/navigator/navigation-options.js
  src/redux/reducers/navigation.js
  src/redux/reducers/navigation.test.js
  src/screens/browser.js
  src/screens/clue.js
  src/screens/context.js
  src/screens/context.test.js
  src/screens/home.js
  src/screens/lesson.js
  src/screens/level-end.js
  src/screens/pdf.js
  src/screens/question.js
  src/screens/splash.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#220 Fix version comparing using semver :hammer_and_wrench:
  flow-typed/npm/semver_v5.1.x.js
  flow-typed/semver-compare.js
  package.json
  src/modules/store.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#215 Enhance video player (Android) and resources UI in correction cards
  .flowconfig
  __e2e__/questions.test.js
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  flow-typed/npm/react-native-portal_vx.x.x.js
  flow-typed/npm/react-navigation_v3.x.x.js
  ios/Coorpacademy.xcodeproj/project.pbxproj
  package.json
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/app.js
  src/components/__snapshots__/authentication.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/video.stories.storyshot
  src/components/correction.js
  src/components/correction.stories.js
  src/components/lesson.js
  src/components/resource.stories.js
  src/components/video.js
  src/containers/card-scalable.js
  src/containers/header.js
  src/containers/progression.js
  src/containers/resource-scalable.js
  src/containers/tab-bar-slide.js
  src/containers/tab-bar.js
  src/containers/video-controlable.js
  src/containers/video-fullscreen-listener.js
  src/containers/with-layout.js
  src/navigator/index.js
  src/redux/actions/navigation.js
  src/redux/actions/navigation.test.js
  src/redux/actions/video.js
  src/redux/actions/video.test.js
  src/redux/reducers/navigation.js
  src/redux/reducers/navigation.test.js
  src/redux/reducers/video.js
  src/redux/reducers/video.test.js
  src/redux/store.js
  src/screens/correction.js
  src/screens/correction.test.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :soon: Waiting for CI

#218 Automatic version bumping
  .circleci/config.yml
  package.json
  scripts/get-version-increment-for-commit.js
  scripts/should-release.js
Labels: pr: :rocket: New feature

#222 Automatic version bumping finalization :rocket:
  .circleci/config.yml
  package.json
  scripts/get-version-increment-for-commit.js
  scripts/should-release.js
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#223 Fix color in tab bar
  flow-typed/npm/react-navigation_v3.x.x.js
  src/containers/tab-bar-slide.js
  src/containers/tab-bar.js
Labels: pr: :bug: Bug Fix

#224 Ignore silent mode on iOS when playing a video
  ios/Coorpacademy.xcodeproj/project.pbxproj
  src/components/video.js
Labels: pr: :lollipop: Enhancement

#226 Fix play pause toggle on iOS
  package.json
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :soon: Waiting for CI

#225 fix sticky button success / fail
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/level-end.js
Labels: pr: :bug: Bug Fix, pr: :soon: Waiting for CI
