Repository CoorpAcademy/mobile, pull requests merged in 2020-07, with the labels that each got.

#564 POC animations
  src/assets/animations/trophy.json
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/trophy.stories.storyshot
  src/components/catalog-item.tsx
  src/components/trophy.tsx
Labels: pr: :lollipop: Enhancement

#569 Switch SplashScreen library
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/coorpacademy/app/MainActivity.java
  android/app/src/main/java/com/coorpacademy/app/SplashActivity.java
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/layout/bootsplash.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-hdpi/icon.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/icon.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/icon.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/icon.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/icon.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Coorpacademy/AppDelegate.m
  ios/Coorpacademy/Base.lproj/LaunchScreen.xib
  ios/Coorpacademy/BootSplash.storyboard
  ios/Coorpacademy/Images.xcassets/BootSplashLogo.imageset/Contents.json
  ios/Coorpacademy/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/Coorpacademy/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/Coorpacademy/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/Coorpacademy/Info.plist
  ios/Podfile.lock
  jest-setup.js
  package.json
  src/assets/images/bootsplash_logo.png
  src/assets/images/bootsplash_logo@1,5x.png
  src/assets/images/bootsplash_logo@2x.png
  src/assets/images/bootsplash_logo@3x.png
  src/assets/images/bootsplash_logo@4x.png
  src/screens/authentication.test.tsx
  src/screens/authentication.tsx
  storybook/index.ts
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review, pr: :no_entry: Do not merge

#574 Android Notification icon
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_notification.png
  android/app/src/main/res/mipmap-mdpi/ic_notification.png
  android/app/src/main/res/mipmap-xhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_notification.png
  android/app/src/main/res/values/colors.xml
Labels: pr: :construction: Work In Progress, pr: :lollipop: Enhancement, pr: :rocket: New feature

#575 Fix empty question screen after validating previous question
  src/redux/actions/ui/answers.ts
Labels: pr: :bug: Bug Fix, pr: :mag_right: Need functional review

#578 Expedit isValidating [tests]
  src/redux/actions/ui/answers.test.ts
Labels: pr: :bug: Bug Fix
