Repository CoorpAcademy/mobile, pull requests merged in 2020-05, with the labels that each got.

#527 <font color=""> support in HTML component
  src/components/__snapshots__/feedback.stories.storyshot
  src/components/__snapshots__/html.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/html.js
  src/components/html.stories.js
  yarn.lock
Labels: pr: :bug: Bug Fix

#528 fix search on search component update
  src/containers/search.js
  src/containers/search.test.js
Labels: pr: :bug: Bug Fix

#529 Fix html's anchor text color
  src/components/__snapshots__/feedback.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/feedback.stories.js
  src/components/html.js
  src/modules/theme.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#533 adding autofocus on search when no params are set
  src/components/__snapshots__/search.stories.storyshot
  src/components/search-input.js
  src/components/search.js
Labels: pr: :lollipop: Enhancement

#531 Fixing env update when yarn start
  package.json
Labels: pr: :bug: Bug Fix

#534 Adding Android back button support
  jest-setup.js
  src/containers/header-left.js
  src/containers/header-left.test.js
  src/containers/video-fullscreen-listener.js
  src/modules/back-handler.js
  src/screens/authentication-details.js
  src/screens/authentication-details.test.js
  src/screens/authentication.js
  src/screens/authentication.test.js
  src/screens/home.js
  src/screens/home.test.js
  src/screens/search.js
  src/screens/search.test.js
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review

#537 Statusbar bug on correction screen
  src/components/__snapshots__/screen.stories.storyshot
  src/components/screen.js
Labels: pr: :bug: Bug Fix

#532 Quick fix for sound in correction screen
  src/components/correction.js
  src/components/correction.stories.js
  src/screens/correction.js
Labels: pr: :bug: Bug Fix, pr: :construction: Work In Progress
