Repository CoorpAcademy/mobile, pull requests merged in 2020-06, with the labels that each got.

#540 Refactoring template parsing
  __e2e__/question-template.test.js
  package.json
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-template.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/question-choices.js
  src/components/question-template.js
  src/modules/template.js
  src/modules/template.test.js
Labels: pr: :bug: Bug Fix, pr: :construction: Work In Progress

#545 Fix react-native 0.62 android auto linking
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
Labels: pr: :mag_right: Need functional review, pr: 🤖Android

#546 Fix camera permissions workflow
  src/redux/actions/permissions.js
  src/redux/actions/permissions.test.js
Labels: pr: :lollipop: Enhancement, pr: :mag_right: Need functional review

#548 reduce ci parallelism
  .circleci/config.yml
Labels: pr: :white_check_mark: Enhance tests

#536 shuffle choices
  package.json
  src/__fixtures__/levels.js
  src/__fixtures__/progression.js
  src/layer/data/_types.js
  src/redux/actions/progressions/create-chapter-progression.js
  src/redux/actions/progressions/create-chapter-progression.test.js
  src/redux/actions/progressions/create-level-progression.js
  src/redux/actions/progressions/create-level-progression.test.js
  src/screens/question.js
  src/screens/question.test.js
  yarn.lock
Labels: pending

#549 Flipper Async Storage Debugger
  index.js
  package.json
  yarn.lock
Labels: pr: :lollipop: Enhancement

#551 Dont shuffle the choices when e2e
  src/redux/actions/progressions/create-chapter-progression.js
  src/redux/actions/progressions/create-level-progression.js
Labels: pr: :bug: Bug Fix

#553 Add GoogleTagManager [542 analytics follow up]
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  src/containers/video-controlable.test.js
  src/layer/data/logger.js
  src/layer/data/logger.test.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#554 Fix E2E Camera Permissions [#542 Follow Up]
  __e2e__/authentication.test.js
  __e2e__/utils.js
  src/const.js
  src/redux/actions/permissions.js
  src/types.js
Labels: pr: :bug: Bug Fix

#552 Fixing interquestion glitch
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/components/question.js
  src/containers/header-slide-title.js
  src/containers/progression.js
  src/containers/progression.test.js
  src/containers/tab-bar-slide.js
  src/redux/actions/ui/answers.js
  src/redux/actions/ui/answers.test.js
  src/redux/reducers/ui/answers.js
  src/redux/reducers/ui/answers.test.js
  src/redux/store.js
  src/redux/utils/state-extract.js
  src/screens/correction.js
  src/screens/correction.test.js
  src/screens/level-end.js
  src/screens/level-end.test.js
  src/screens/question.js
  src/screens/question.test.js
Labels: pr: :bug: Bug Fix

#557 Adding notifyMe screen
  src/assets/images/notify-me-bg@2x.png
  src/components/__snapshots__/notify-me.stories.storyshot
  src/components/notify-me.stories.tsx
  src/components/notify-me.tsx
  src/navigator/index.tsx
  src/screens/home.tsx
  src/screens/notifications.test.tsx
  src/screens/notifications.tsx
  src/stories.ts
Labels: pr: :construction: Work In Progress, pr: :lollipop: Enhancement, pr: :rocket: New feature
