Repository CoorpAcademy/mobile, pull requests merged in 2020-04, with the labels that each got.

#504 Fetch Youtube API Key From Config
  src/__fixtures__/brands.js
  src/__fixtures__/store.test.js
  src/components/__snapshots__/brand-theme-provider.stories.storyshot
  src/components/brand-theme-provider.js
  src/components/video-youtube.js
  src/components/video-youtube.stories.js
  src/containers/video-youtube.js
  src/containers/video-youtube.test.js
  src/layer/data/brand.js
  src/layer/data/brand.test.js
  src/redux/utils/state-extract.js
  src/redux/utils/state-extract.test.js
  src/types.js
Labels: pr: :bug: Bug Fix, pr: 🤖Android

#488 Post errors to datadog
  android/fastlane/Fastfile
  app.json
  flow-typed/custom/serialize-error_v6.x.x.js
  ios/fastlane/Fastfile
  package.json
  scripts/update-version.js
  src/__fixtures__/brands.js
  src/__fixtures__/store.test.js
  src/components/__snapshots__/brand-theme-provider.stories.storyshot
  src/components/brand-theme-provider.js
  src/layer/data/brand.js
  src/layer/data/brand.test.js
  src/layer/data/logger.js
  src/layer/data/logger.test.js
  src/modules/datadog.js
  src/modules/datadog.test.js
  src/modules/environment.js
  src/modules/environment.test.js
  src/modules/store.js
  src/modules/store.test.js
  src/modules/version.js.flow
  src/redux/actions/authentication.js
  src/types.js
  src/utils/local-brand.js
  src/utils/local-brand.test.js
  src/utils/local-token.js
  src/utils/local-token.test.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#505 Fix409 e
  src/__fixtures__/store.js
  src/__fixtures__/store.test.js
  src/layer/data/progressions.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/redux/reducers/progressions/synchronize.js
  src/redux/reducers/progressions/synchronize.test.js
  src/redux/store.js
  src/redux/utils/state-extract.js
Labels: pr: :bug: Bug Fix

#510 Use flavors from version file instead of env var
  metro.config.js
Labels: pr: :wrench: Refactoring

#508 Add BR support
  __e2e__/question-template.test.js
  src/__fixtures__/questions.js
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-template.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/question-choices.stories.js
  src/components/question-template.js
  src/components/question-template.stories.js
  src/modules/template.js
  src/modules/template.test.js
  src/screens/question.test.js
Labels: pr: :bug: Bug Fix

#517 Fix design
  src/components/__snapshots__/clue.stories.storyshot
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/drop-zone.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/question-choice.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-draggable.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/clue.js
  src/components/context.js
  src/components/lesson.js
  src/components/question-choice.js
Labels: pr: :lollipop: Enhancement

#519 Fix errors thrown by mobile app
  package.json
  src/services/index.js
  src/services/index.test.js
  yarn.lock
Labels: pr: :bug: Bug Fix

#526 Add User-Agent for errors logs
  src/app.js
  src/layer/data/progressions.test.js
  src/modules/build.js
  src/modules/build.test.js
  src/modules/datadog.js
  src/modules/datadog.test.js
  src/modules/fetch.js
  src/modules/fetch.test.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring
