Repository CoorpAcademy/mobile, pull requests merged in 2020-09, with the labels that each got.

#596 Installing AWS CLI on CI
  .circleci/adhoc-template.plist
  .circleci/config.yml
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#598 Fix completion for adaptive courses with more than a level
  src/components/__snapshots__/catalog-item-footer.stories.storyshot
  src/components/catalog-item-footer.stories.tsx
  src/components/catalog-item-footer.tsx
Labels: pr: :bug: Bug Fix

#599 Adding filter on fetch content to exclude everything but lessons and courses
  src/__fixtures__/cards.ts
  src/layer/data/cards.test.ts
  src/layer/data/cards.ts
Labels: pr: :bug: Bug Fix

#600 Fix persist allowlist
  src/redux/store.ts
Labels: pr: :bug: Bug Fix

#602 Exclude external content (part 2)
  src/layer/data/cards.test.ts
  src/layer/data/cards.ts
  src/migrations/runner.ts
  src/migrations/scripts/fix-progressions-answers/index.test.ts
  src/migrations/types.ts
Labels: pr: :bug: Bug Fix

#604 Recommendations[Exclude external content]
  src/layer/data/recommendations.test.ts
  src/layer/data/recommendations.ts
Labels: pr: :bug: Bug Fix

#608 updating gitignore
  .gitignore
Labels: pr: :lollipop: Enhancement

#610 Suggestion notification [follow up]
  __e2e__/notifications-dont-notifyme.test.ts
  __e2e__/notifications-notifyme.test.ts
  app.json
  ios/Podfile.lock
  jest-setup.js
  scripts/pull-translations.js
  src/components/__snapshots__/settings.stories.storyshot
  src/components/settings.stories.tsx
  src/components/settings.tsx
  src/const.ts
  src/layer/data/recommendations.ts
  src/redux/actions/notifications/scheduled-notifications.test.ts
  src/redux/actions/notifications/scheduled-notifications.ts
  src/redux/actions/notifications/settings.test.ts
  src/redux/actions/notifications/settings.ts
  src/redux/migrate.test.ts
  src/redux/migrate.ts
  src/redux/reducers/notifications/scheduled-notifications.test.ts
  src/redux/reducers/notifications/scheduled-notifications.ts
  src/redux/reducers/notifications/settings.test.ts
  src/redux/reducers/notifications/settings.ts
  src/redux/store.ts
  src/services/notification-content.ts
  src/translations/_types.ts
  src/translations/cs.ts
  src/translations/de.ts
  src/translations/en.ts
  src/translations/es.ts
  src/translations/fr.ts
  src/translations/hu.ts
  src/translations/it.ts
  src/translations/ja.ts
  src/translations/ko.ts
  src/translations/nl.ts
  src/translations/pl.ts
  src/translations/pt.ts
  src/translations/ro.ts
  src/translations/ru.ts
  src/translations/tr.ts
  src/translations/uk.ts
  src/translations/vi.ts
  src/translations/zh-tw.ts
  src/translations/zh.ts
  src/types.ts
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#613 Notifications Analytics[follow up]
  src/notification-handler.ts
  src/redux/actions/notifications/scheduled-notifications.ts
Labels: pr: :lollipop: Enhancement

#612 Fix some types
  src/layer/data/_const.ts
  src/layer/data/_types.ts
  src/redux/store.ts
  src/redux/utils/reset-on-logout.test.ts
  src/redux/utils/reset-on-logout.ts
  src/types.ts
  src/types/coorpacademy/player-services/index.ts
  src/types/coorpacademy/player-services/recommendations.ts
Labels: pr: :lollipop: Enhancement

#614 Deactivates notifs when none is activated
  __e2e__/notifications-notifyme.test.ts
  src/redux/reducers/notifications/settings.test.ts
  src/redux/reducers/notifications/settings.ts
Labels: pr: :lollipop: Enhancement

#615 Drop catalog card shadow
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-items.stories.storyshot
  src/components/__snapshots__/catalog-search.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/feedback.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/notification-card.stories.storyshot
  src/components/__snapshots__/notify-me.stories.storyshot
  src/components/card.tsx
Labels: pr: :bug: Bug Fix
