Repository CoorpAcademy/mobile, pull requests merged in 2020-02, with the labels that each got.

#473 Flatten Header component and remove absolute things
  __e2e__/authentication.test.js
  src/components/__snapshots__/authentication-details.stories.storyshot
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-items.stories.storyshot
  src/components/__snapshots__/catalog-search.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/header-back-button.stories.storyshot
  src/components/__snapshots__/header.stories.storyshot
  src/components/__snapshots__/home.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/modal-error.stories.storyshot
  src/components/__snapshots__/modal-select.stories.storyshot
  src/components/__snapshots__/modal.stories.storyshot
  src/components/__snapshots__/question-choices.stories.storyshot
  src/components/__snapshots__/question-input.stories.storyshot
  src/components/__snapshots__/question-template.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/search-input.stories.storyshot
  src/components/__snapshots__/select.stories.storyshot
  src/components/header-back-button.js
  src/components/header-back-button.stories.js
  src/components/header.js
  src/components/header.stories.js
  src/components/search-input.js
  src/components/search-input.stories.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#474 Fix card display in level end and explicit deck cards names
  __e2e__/correction.resources.test.js
  __e2e__/questions.test.js
  src/components/__snapshots__/card.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/deck-card-correction.stories.storyshot
  src/components/__snapshots__/deck-card-header.stories.storyshot
  src/components/__snapshots__/deck-card.stories.storyshot
  src/components/__snapshots__/deck-cards.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/card-header.stories.js
  src/components/card.js
  src/components/card.stories.js
  src/components/catalog-item.js
  src/components/correction.js
  src/components/deck-card-correction.js
  src/components/deck-card-correction.stories.js
  src/components/deck-card-header.js
  src/components/deck-card-header.stories.js
  src/components/deck-card.js
  src/components/deck-card.stories.js
  src/components/deck-cards.js
  src/components/deck-cards.stories.js
  src/components/level-end.js
  src/const.js
  src/containers/deck-card-scalable.js
  src/containers/deck-cards-swipable.js
  src/containers/deck-cards-swipable.test.js
  src/screens/correction.test.js
  src/stories.js
  src/types.js
Labels: pr: :bug: Bug Fix, pr: :wrench: Refactoring

#477 Change progression bar color to green instead of brands one
  src/components/__snapshots__/catalog-item-content.stories.storyshot
  src/components/__snapshots__/catalog-item-footer.stories.storyshot
  src/components/__snapshots__/catalog-item.stories.storyshot
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/__snapshots__/catalog.stories.storyshot
  src/components/__snapshots__/hero.stories.storyshot
  src/components/__snapshots__/level-end.stories.storyshot
  src/components/__snapshots__/progression-bar.stories.storyshot
  src/components/__snapshots__/progression.stories.storyshot
  src/components/progression-bar.js
Labels: pr: :lollipop: Enhancement
