Repository CoorpAcademy/mobile, pull requests merged in 2020-03, with the labels that each got.

#479 Fix best score in e2e mode
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
Labels: pr: :bug: Bug Fix

#478 Add another domain for https proxy domain
  .circleci/config.yml
Labels: pr: :soon: Waiting for CI, pr: :wrench: Refactoring

#480 Add scroll on search result
  __e2e__/utils.js
  jest.config.unit.js
  src/components/__snapshots__/catalog-section.stories.storyshot
  src/components/catalog-items.js
  src/components/catalog-search.js
  src/components/catalog-section.js
  src/components/catalog.js
  src/containers/catalog-items.js
  src/containers/catalog-items.test.js
  src/containers/catalog-search.js
  src/containers/catalog-search.test.js
  src/containers/catalog-section-refreshable.js
  src/containers/catalog-section.js
  src/containers/catalog-section.test.js
Labels: pr: :rocket: New feature

#481 Home indicator
  src/components/__snapshots__/screen.stories.storyshot
  src/components/screen.js
Labels: pr: :lollipop: Enhancement

#482 Upgrade node@12
  .circleci/config.yml
  .nvmrc
  src/redux/actions/progressions/synchronize.test.js
Labels: pr: :wrench: Refactoring

#486 Skip fetch in case of e2e
  jest-setup.js
  src/layer/data/brand.test.js
  src/layer/data/bundle.test.js
  src/layer/data/cards.test.js
  src/layer/data/content.test.js
  src/layer/data/language.test.js
  src/layer/data/levels.test.js
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/layer/data/recommendations.test.js
  src/layer/data/sections.test.js
  src/layer/data/users.test.js
  src/layer/data/videos.test.js
  src/modules/fetch.js
  src/modules/fetch.test.js
  src/modules/store.test.js
  src/redux/actions/authentication.test.js
Labels: pr: :wrench: Refactoring

#487 Fix409
  src/layer/data/index.js
  src/layer/data/index.test.js
  src/layer/data/progressions.js
  src/layer/data/progressions.test.js
  src/redux/actions/progressions/synchronize.js
  src/redux/actions/progressions/synchronize.test.js
  src/services/progressions.js
Labels: pr: :bug: Bug Fix

#493 fix correction link browser
  src/__fixtures__/slides.js
  src/components/__snapshots__/correction.stories.storyshot
  src/components/correction.js
  src/components/correction.stories.js
  src/screens/correction.js
  src/screens/correction.test.js
Labels: pr: :bug: Bug Fix

#492 Omniplayer video incrusted
  package.json
  src/__fixtures__/discipline-bundle/basic.js
  src/__fixtures__/lessons.js
  src/__fixtures__/videos.js
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/correction.stories.storyshot
  src/components/__snapshots__/lesson.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/resource.js
  src/components/resource.stories.js
  src/components/video.js
  src/const.js
  src/layer/data/_const.js
  src/modules/uri.js
  src/screens/context.js
  src/screens/context.test.js
  src/types.js
  yarn.lock
Labels: pr: :construction: Work In Progress

#495 Adding youtube video player
  android/app/build.gradle
  android/app/src/main/java/com/coorpacademy/app/MainApplication.java
  android/settings.gradle
  ios/Coorpacademy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/__fixtures__/context.js
  src/__fixtures__/lessons.js
  src/components/__snapshots__/context.stories.storyshot
  src/components/__snapshots__/question.stories.storyshot
  src/components/__snapshots__/resource-video.stories.storyshot
  src/components/__snapshots__/resource.stories.storyshot
  src/components/__snapshots__/video-omniplayer.stories.storyshot
  src/components/__snapshots__/video-overlay.stories.storyshot
  src/components/__snapshots__/video-youtube.stories.storyshot
  src/components/__snapshots__/video.stories.storyshot
  src/components/resource-video.js
  src/components/resource-video.stories.js
  src/components/resource.js
  src/components/resource.stories.js
  src/components/video-omniplayer.js
  src/components/video-omniplayer.stories.js
  src/components/video-overlay.js
  src/components/video-overlay.stories.js
  src/components/video-youtube.js
  src/components/video-youtube.stories.js
  src/components/video.js
  src/components/video.stories.js
  src/const.js
  src/containers/video-youtube.js
  src/containers/video-youtube.test.js
  src/layer/data/_const.js
  src/modules/media.js
  src/modules/media.test.js
  src/stories.js
  src/types.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature
